# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\umt_work.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UMT_Auswertung(object):
    def setupUi(self, UMT_Auswertung):
        UMT_Auswertung.setObjectName("UMT_Auswertung")
        UMT_Auswertung.resize(720, 823)
        self.centralwidget = QtWidgets.QWidget(UMT_Auswertung)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gb_inout = QtWidgets.QGroupBox(self.centralwidget)
        self.gb_inout.setMaximumSize(QtCore.QSize(16777215, 150))
        self.gb_inout.setObjectName("gb_inout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.gb_inout)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_17 = QtWidgets.QLabel(self.gb_inout)
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 1, 0, 1, 1)
        self.tool_input_file = QtWidgets.QToolButton(self.gb_inout)
        self.tool_input_file.setObjectName("tool_input_file")
        self.gridLayout_4.addWidget(self.tool_input_file, 0, 2, 1, 1)
        self.lab_source = QtWidgets.QLabel(self.gb_inout)
        self.lab_source.setObjectName("lab_source")
        self.gridLayout_4.addWidget(self.lab_source, 0, 0, 1, 1)
        self.txt_input_file = QtWidgets.QLineEdit(self.gb_inout)
        self.txt_input_file.setMinimumSize(QtCore.QSize(200, 0))
        self.txt_input_file.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.txt_input_file.setFrame(True)
        self.txt_input_file.setDragEnabled(False)
        self.txt_input_file.setClearButtonEnabled(False)
        self.txt_input_file.setObjectName("txt_input_file")
        self.gridLayout_4.addWidget(self.txt_input_file, 0, 1, 1, 1)
        self.txt_output_pics = QtWidgets.QLineEdit(self.gb_inout)
        self.txt_output_pics.setMinimumSize(QtCore.QSize(200, 0))
        self.txt_output_pics.setFrame(True)
        self.txt_output_pics.setDragEnabled(False)
        self.txt_output_pics.setClearButtonEnabled(False)
        self.txt_output_pics.setObjectName("txt_output_pics")
        self.gridLayout_4.addWidget(self.txt_output_pics, 1, 1, 1, 1)
        self.tool_output_pics = QtWidgets.QToolButton(self.gb_inout)
        self.tool_output_pics.setObjectName("tool_output_pics")
        self.gridLayout_4.addWidget(self.tool_output_pics, 1, 2, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout_4)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.but_clear_data = QtWidgets.QPushButton(self.gb_inout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.but_clear_data.sizePolicy().hasHeightForWidth())
        self.but_clear_data.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.but_clear_data.setFont(font)
        self.but_clear_data.setObjectName("but_clear_data")
        self.horizontalLayout_4.addWidget(self.but_clear_data)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.line_2 = QtWidgets.QFrame(self.gb_inout)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_4.addWidget(self.line_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.gb_inout)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1, QtCore.Qt.AlignRight)
        self.txt_para_frequency = QtWidgets.QLineEdit(self.gb_inout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_para_frequency.sizePolicy().hasHeightForWidth())
        self.txt_para_frequency.setSizePolicy(sizePolicy)
        self.txt_para_frequency.setMaximumSize(QtCore.QSize(30, 16777215))
        self.txt_para_frequency.setObjectName("txt_para_frequency")
        self.gridLayout.addWidget(self.txt_para_frequency, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gb_inout)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1, QtCore.Qt.AlignRight)
        self.txt_para_hub = QtWidgets.QLineEdit(self.gb_inout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_para_hub.sizePolicy().hasHeightForWidth())
        self.txt_para_hub.setSizePolicy(sizePolicy)
        self.txt_para_hub.setMaximumSize(QtCore.QSize(30, 16777215))
        self.txt_para_hub.setObjectName("txt_para_hub")
        self.gridLayout.addWidget(self.txt_para_hub, 1, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.gb_inout)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 0, 2, 1, 1, QtCore.Qt.AlignLeft)
        self.label_19 = QtWidgets.QLabel(self.gb_inout)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 1, 2, 1, 1, QtCore.Qt.AlignLeft)
        self.horizontalLayout_6.addLayout(self.gridLayout)
        spacerItem1 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.but_calc_s = QtWidgets.QPushButton(self.gb_inout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.but_calc_s.sizePolicy().hasHeightForWidth())
        self.but_calc_s.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(True)
        self.but_calc_s.setFont(font)
        self.but_calc_s.setObjectName("but_calc_s")
        self.horizontalLayout_6.addWidget(self.but_calc_s)
        spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setContentsMargins(10, -1, -1, -1)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.cb_save_pic_raw = QtWidgets.QCheckBox(self.gb_inout)
        self.cb_save_pic_raw.setObjectName("cb_save_pic_raw")
        self.verticalLayout_19.addWidget(self.cb_save_pic_raw)
        self.but_plot_raw = QtWidgets.QPushButton(self.gb_inout)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.but_plot_raw.setFont(font)
        self.but_plot_raw.setObjectName("but_plot_raw")
        self.verticalLayout_19.addWidget(self.but_plot_raw)
        self.horizontalLayout_6.addLayout(self.verticalLayout_19)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.verticalLayout.addWidget(self.gb_inout)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setContentsMargins(-1, 5, -1, -1)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.but_collapse_settings = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.but_collapse_settings.setFont(font)
        self.but_collapse_settings.setObjectName("but_collapse_settings")
        self.horizontalLayout_23.addWidget(self.but_collapse_settings)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem4)
        self.verticalLayout_12.addLayout(self.horizontalLayout_23)
        self.scroll_settings = QtWidgets.QScrollArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scroll_settings.sizePolicy().hasHeightForWidth())
        self.scroll_settings.setSizePolicy(sizePolicy)
        self.scroll_settings.setMinimumSize(QtCore.QSize(0, 0))
        self.scroll_settings.setMaximumSize(QtCore.QSize(16777215, 292))
        self.scroll_settings.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scroll_settings.setMidLineWidth(0)
        self.scroll_settings.setWidgetResizable(True)
        self.scroll_settings.setObjectName("scroll_settings")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 700, 292))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gb_minima = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_3)
        self.gb_minima.setObjectName("gb_minima")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.gb_minima)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.gb_minima)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1, QtCore.Qt.AlignRight)
        self.txt_para_min_dist = QtWidgets.QLineEdit(self.gb_minima)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_para_min_dist.sizePolicy().hasHeightForWidth())
        self.txt_para_min_dist.setSizePolicy(sizePolicy)
        self.txt_para_min_dist.setMaximumSize(QtCore.QSize(30, 16777215))
        self.txt_para_min_dist.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_para_min_dist.setObjectName("txt_para_min_dist")
        self.gridLayout_2.addWidget(self.txt_para_min_dist, 1, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.txt_para_min_n = QtWidgets.QLineEdit(self.gb_minima)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_para_min_n.sizePolicy().hasHeightForWidth())
        self.txt_para_min_n.setSizePolicy(sizePolicy)
        self.txt_para_min_n.setMaximumSize(QtCore.QSize(30, 16777215))
        self.txt_para_min_n.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_para_min_n.setObjectName("txt_para_min_n")
        self.gridLayout_2.addWidget(self.txt_para_min_n, 2, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.label_6 = QtWidgets.QLabel(self.gb_minima)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1, QtCore.Qt.AlignRight)
        self.label_5 = QtWidgets.QLabel(self.gb_minima)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1, QtCore.Qt.AlignRight)
        self.txt_para_min_thresh = QtWidgets.QLineEdit(self.gb_minima)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_para_min_thresh.sizePolicy().hasHeightForWidth())
        self.txt_para_min_thresh.setSizePolicy(sizePolicy)
        self.txt_para_min_thresh.setMaximumSize(QtCore.QSize(30, 16777215))
        self.txt_para_min_thresh.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_para_min_thresh.setObjectName("txt_para_min_thresh")
        self.gridLayout_2.addWidget(self.txt_para_min_thresh, 0, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.label_7 = QtWidgets.QLabel(self.gb_minima)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 3, 0, 1, 1, QtCore.Qt.AlignRight)
        self.txt_para_min_pos = QtWidgets.QLineEdit(self.gb_minima)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_para_min_pos.sizePolicy().hasHeightForWidth())
        self.txt_para_min_pos.setSizePolicy(sizePolicy)
        self.txt_para_min_pos.setMinimumSize(QtCore.QSize(0, 0))
        self.txt_para_min_pos.setMaximumSize(QtCore.QSize(35, 16777215))
        self.txt_para_min_pos.setObjectName("txt_para_min_pos")
        self.gridLayout_2.addWidget(self.txt_para_min_pos, 3, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.horizontalLayout_3.addLayout(self.gridLayout_2)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setContentsMargins(0, 0, -1, -1)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.cb_save_pic_min = QtWidgets.QCheckBox(self.gb_minima)
        self.cb_save_pic_min.setObjectName("cb_save_pic_min")
        self.verticalLayout_23.addWidget(self.cb_save_pic_min, 0, QtCore.Qt.AlignHCenter)
        self.but_plot_min = QtWidgets.QPushButton(self.gb_minima)
        self.but_plot_min.setObjectName("but_plot_min")
        self.verticalLayout_23.addWidget(self.but_plot_min)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_23.addItem(spacerItem6)
        self.but_min_ok = QtWidgets.QPushButton(self.gb_minima)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.but_min_ok.setFont(font)
        self.but_min_ok.setObjectName("but_min_ok")
        self.verticalLayout_23.addWidget(self.but_min_ok)
        self.horizontalLayout_3.addLayout(self.verticalLayout_23)
        self.horizontalLayout.addWidget(self.gb_minima)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem8)
        self.gb_dist = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_3)
        self.gb_dist.setEnabled(False)
        self.gb_dist.setObjectName("gb_dist")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.gb_dist)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_8 = QtWidgets.QLabel(self.gb_dist)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 0, 0, 1, 1, QtCore.Qt.AlignRight)
        self.txt_para_dist_thresh = QtWidgets.QLineEdit(self.gb_dist)
        self.txt_para_dist_thresh.setMaximumSize(QtCore.QSize(30, 16777215))
        self.txt_para_dist_thresh.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_para_dist_thresh.setObjectName("txt_para_dist_thresh")
        self.gridLayout_3.addWidget(self.txt_para_dist_thresh, 0, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.label_9 = QtWidgets.QLabel(self.gb_dist)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 1, 0, 1, 1, QtCore.Qt.AlignRight)
        self.txt_para_dist_off = QtWidgets.QLineEdit(self.gb_dist)
        self.txt_para_dist_off.setMaximumSize(QtCore.QSize(30, 16777215))
        self.txt_para_dist_off.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_para_dist_off.setObjectName("txt_para_dist_off")
        self.gridLayout_3.addWidget(self.txt_para_dist_off, 1, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.horizontalLayout_5.addLayout(self.gridLayout_3)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem9)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cb_save_pic_dist = QtWidgets.QCheckBox(self.gb_dist)
        self.cb_save_pic_dist.setObjectName("cb_save_pic_dist")
        self.verticalLayout_2.addWidget(self.cb_save_pic_dist, 0, QtCore.Qt.AlignHCenter)
        self.but_plot_dist = QtWidgets.QPushButton(self.gb_dist)
        self.but_plot_dist.setObjectName("but_plot_dist")
        self.verticalLayout_2.addWidget(self.but_plot_dist)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem10)
        self.but_dist_ok = QtWidgets.QPushButton(self.gb_dist)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.but_dist_ok.setFont(font)
        self.but_dist_ok.setObjectName("but_dist_ok")
        self.verticalLayout_2.addWidget(self.but_dist_ok)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.horizontalLayout.addWidget(self.gb_dist)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem11)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem12)
        self.gb_area = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_3)
        self.gb_area.setEnabled(False)
        self.gb_area.setObjectName("gb_area")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.gb_area)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.txt_para_area_shift = QtWidgets.QLineEdit(self.gb_area)
        self.txt_para_area_shift.setMaximumSize(QtCore.QSize(30, 16777215))
        self.txt_para_area_shift.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_para_area_shift.setObjectName("txt_para_area_shift")
        self.gridLayout_5.addWidget(self.txt_para_area_shift, 0, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.txt_para_area_n = QtWidgets.QLineEdit(self.gb_area)
        self.txt_para_area_n.setMaximumSize(QtCore.QSize(30, 16777215))
        self.txt_para_area_n.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_para_area_n.setObjectName("txt_para_area_n")
        self.gridLayout_5.addWidget(self.txt_para_area_n, 1, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.label_10 = QtWidgets.QLabel(self.gb_area)
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 0, 0, 1, 1, QtCore.Qt.AlignRight)
        self.label_11 = QtWidgets.QLabel(self.gb_area)
        self.label_11.setObjectName("label_11")
        self.gridLayout_5.addWidget(self.label_11, 1, 0, 1, 1, QtCore.Qt.AlignRight)
        self.label_12 = QtWidgets.QLabel(self.gb_area)
        self.label_12.setObjectName("label_12")
        self.gridLayout_5.addWidget(self.label_12, 2, 0, 1, 1, QtCore.Qt.AlignRight)
        self.txt_para_area_pos = QtWidgets.QLineEdit(self.gb_area)
        self.txt_para_area_pos.setMaximumSize(QtCore.QSize(35, 16777215))
        self.txt_para_area_pos.setObjectName("txt_para_area_pos")
        self.gridLayout_5.addWidget(self.txt_para_area_pos, 2, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.horizontalLayout_8.addLayout(self.gridLayout_5)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem13)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.cb_save_pic_area = QtWidgets.QCheckBox(self.gb_area)
        self.cb_save_pic_area.setObjectName("cb_save_pic_area")
        self.verticalLayout_5.addWidget(self.cb_save_pic_area)
        self.but_plot_area = QtWidgets.QPushButton(self.gb_area)
        self.but_plot_area.setObjectName("but_plot_area")
        self.verticalLayout_5.addWidget(self.but_plot_area)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem14)
        self.but_area_ok = QtWidgets.QPushButton(self.gb_area)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.but_area_ok.setFont(font)
        self.but_area_ok.setObjectName("but_area_ok")
        self.verticalLayout_5.addWidget(self.but_area_ok)
        self.horizontalLayout_8.addLayout(self.verticalLayout_5)
        self.horizontalLayout.addWidget(self.gb_area)
        self.verticalLayout_13.addLayout(self.horizontalLayout)
        self.line = QtWidgets.QFrame(self.scrollAreaWidgetContents_3)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_13.addWidget(self.line)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.gb_filter = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_3)
        self.gb_filter.setEnabled(False)
        self.gb_filter.setObjectName("gb_filter")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.gb_filter)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setContentsMargins(10, 10, -1, -1)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.rb_filt_roll = QtWidgets.QRadioButton(self.gb_filter)
        self.rb_filt_roll.setObjectName("rb_filt_roll")
        self.gridLayout_6.addWidget(self.rb_filt_roll, 1, 0, 1, 1)
        self.rb_filt_sav = QtWidgets.QRadioButton(self.gb_filter)
        self.rb_filt_sav.setChecked(True)
        self.rb_filt_sav.setObjectName("rb_filt_sav")
        self.gridLayout_6.addWidget(self.rb_filt_sav, 0, 0, 1, 1)
        self.lab_p_sav = QtWidgets.QLabel(self.gb_filter)
        self.lab_p_sav.setObjectName("lab_p_sav")
        self.gridLayout_6.addWidget(self.lab_p_sav, 0, 3, 1, 1)
        self.txt_para_filt_n_sav = QtWidgets.QLineEdit(self.gb_filter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_para_filt_n_sav.sizePolicy().hasHeightForWidth())
        self.txt_para_filt_n_sav.setSizePolicy(sizePolicy)
        self.txt_para_filt_n_sav.setMinimumSize(QtCore.QSize(30, 0))
        self.txt_para_filt_n_sav.setMaximumSize(QtCore.QSize(35, 16777215))
        self.txt_para_filt_n_sav.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_para_filt_n_sav.setObjectName("txt_para_filt_n_sav")
        self.gridLayout_6.addWidget(self.txt_para_filt_n_sav, 0, 2, 1, 1)
        self.lab_n_sav = QtWidgets.QLabel(self.gb_filter)
        self.lab_n_sav.setObjectName("lab_n_sav")
        self.gridLayout_6.addWidget(self.lab_n_sav, 0, 1, 1, 1)
        self.txt_para_filt_n_roll = QtWidgets.QLineEdit(self.gb_filter)
        self.txt_para_filt_n_roll.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_para_filt_n_roll.sizePolicy().hasHeightForWidth())
        self.txt_para_filt_n_roll.setSizePolicy(sizePolicy)
        self.txt_para_filt_n_roll.setMaximumSize(QtCore.QSize(35, 16777215))
        self.txt_para_filt_n_roll.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_para_filt_n_roll.setObjectName("txt_para_filt_n_roll")
        self.gridLayout_6.addWidget(self.txt_para_filt_n_roll, 1, 2, 1, 1)
        self.txt_para_filt_p_sav = QtWidgets.QLineEdit(self.gb_filter)
        self.txt_para_filt_p_sav.setMaximumSize(QtCore.QSize(20, 16777215))
        self.txt_para_filt_p_sav.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_para_filt_p_sav.setObjectName("txt_para_filt_p_sav")
        self.gridLayout_6.addWidget(self.txt_para_filt_p_sav, 0, 4, 1, 1)
        self.lab_n_roll = QtWidgets.QLabel(self.gb_filter)
        self.lab_n_roll.setEnabled(False)
        self.lab_n_roll.setObjectName("lab_n_roll")
        self.gridLayout_6.addWidget(self.lab_n_roll, 1, 1, 1, 1)
        self.rb_filt_med = QtWidgets.QRadioButton(self.gb_filter)
        self.rb_filt_med.setObjectName("rb_filt_med")
        self.gridLayout_6.addWidget(self.rb_filt_med, 2, 0, 1, 1)
        self.lab_n_med = QtWidgets.QLabel(self.gb_filter)
        self.lab_n_med.setEnabled(False)
        self.lab_n_med.setObjectName("lab_n_med")
        self.gridLayout_6.addWidget(self.lab_n_med, 2, 1, 1, 1)
        self.txt_para_filt_n_med = QtWidgets.QLineEdit(self.gb_filter)
        self.txt_para_filt_n_med.setEnabled(False)
        self.txt_para_filt_n_med.setMaximumSize(QtCore.QSize(35, 16777215))
        self.txt_para_filt_n_med.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_para_filt_n_med.setObjectName("txt_para_filt_n_med")
        self.gridLayout_6.addWidget(self.txt_para_filt_n_med, 2, 2, 1, 1)
        self.horizontalLayout_18.addLayout(self.gridLayout_6)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem15)
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.cb_save_pic_filt = QtWidgets.QCheckBox(self.gb_filter)
        self.cb_save_pic_filt.setObjectName("cb_save_pic_filt")
        self.verticalLayout_22.addWidget(self.cb_save_pic_filt, 0, QtCore.Qt.AlignHCenter)
        self.but_plot_filt = QtWidgets.QPushButton(self.gb_filter)
        self.but_plot_filt.setObjectName("but_plot_filt")
        self.verticalLayout_22.addWidget(self.but_plot_filt)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_22.addItem(spacerItem16)
        self.but_filt_ok = QtWidgets.QPushButton(self.gb_filter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.but_filt_ok.setFont(font)
        self.but_filt_ok.setObjectName("but_filt_ok")
        self.verticalLayout_22.addWidget(self.but_filt_ok)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_22.addItem(spacerItem17)
        self.horizontalLayout_18.addLayout(self.verticalLayout_22)
        self.horizontalLayout_7.addWidget(self.gb_filter)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem18)
        self.gb_cof = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_3)
        self.gb_cof.setEnabled(False)
        self.gb_cof.setObjectName("gb_cof")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.gb_cof)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setContentsMargins(-1, -1, 0, 0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(0, 0, -1, -1)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.rb_cof_t = QtWidgets.QRadioButton(self.gb_cof)
        self.rb_cof_t.setChecked(True)
        self.rb_cof_t.setObjectName("rb_cof_t")
        self.horizontalLayout_12.addWidget(self.rb_cof_t)
        self.rb_cof_s = QtWidgets.QRadioButton(self.gb_cof)
        self.rb_cof_s.setChecked(False)
        self.rb_cof_s.setObjectName("rb_cof_s")
        self.horizontalLayout_12.addWidget(self.rb_cof_s)
        self.verticalLayout_7.addLayout(self.horizontalLayout_12)
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.lab_cof_end = QtWidgets.QLabel(self.gb_cof)
        self.lab_cof_end.setObjectName("lab_cof_end")
        self.gridLayout_15.addWidget(self.lab_cof_end, 1, 2, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.gb_cof)
        self.label_26.setObjectName("label_26")
        self.gridLayout_15.addWidget(self.label_26, 1, 0, 1, 1)
        self.txt_para_cof_start = QtWidgets.QLineEdit(self.gb_cof)
        self.txt_para_cof_start.setMaximumSize(QtCore.QSize(45, 16777215))
        self.txt_para_cof_start.setText("")
        self.txt_para_cof_start.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_para_cof_start.setObjectName("txt_para_cof_start")
        self.gridLayout_15.addWidget(self.txt_para_cof_start, 0, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.gb_cof)
        self.label_25.setObjectName("label_25")
        self.gridLayout_15.addWidget(self.label_25, 0, 0, 1, 1)
        self.lab_cof_start = QtWidgets.QLabel(self.gb_cof)
        self.lab_cof_start.setObjectName("lab_cof_start")
        self.gridLayout_15.addWidget(self.lab_cof_start, 0, 2, 1, 1)
        self.txt_para_cof_end = QtWidgets.QLineEdit(self.gb_cof)
        self.txt_para_cof_end.setMaximumSize(QtCore.QSize(45, 16777215))
        self.txt_para_cof_end.setText("")
        self.txt_para_cof_end.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_para_cof_end.setObjectName("txt_para_cof_end")
        self.gridLayout_15.addWidget(self.txt_para_cof_end, 1, 1, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_15)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem19)
        self.horizontalLayout_21.addLayout(self.verticalLayout_7)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem20)
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_21.setSpacing(0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.cb_save_pic_cof = QtWidgets.QCheckBox(self.gb_cof)
        self.cb_save_pic_cof.setObjectName("cb_save_pic_cof")
        self.verticalLayout_21.addWidget(self.cb_save_pic_cof, 0, QtCore.Qt.AlignHCenter)
        self.but_plot_cof = QtWidgets.QPushButton(self.gb_cof)
        self.but_plot_cof.setObjectName("but_plot_cof")
        self.verticalLayout_21.addWidget(self.but_plot_cof)
        spacerItem21 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_21.addItem(spacerItem21)
        self.but_cof_ok = QtWidgets.QPushButton(self.gb_cof)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.but_cof_ok.setFont(font)
        self.but_cof_ok.setObjectName("but_cof_ok")
        self.verticalLayout_21.addWidget(self.but_cof_ok)
        spacerItem22 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_21.addItem(spacerItem22)
        self.horizontalLayout_21.addLayout(self.verticalLayout_21)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_7.addWidget(self.gb_cof)
        self.verticalLayout_13.addLayout(self.horizontalLayout_7)
        self.scroll_settings.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_12.addWidget(self.scroll_settings)
        self.verticalLayout.addLayout(self.verticalLayout_12)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setContentsMargins(-1, 5, -1, -1)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.but_collapse_export = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.but_collapse_export.setFont(font)
        self.but_collapse_export.setObjectName("but_collapse_export")
        self.horizontalLayout_25.addWidget(self.but_collapse_export)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem23)
        self.verticalLayout_14.addLayout(self.horizontalLayout_25)
        self.scroll_export = QtWidgets.QScrollArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scroll_export.sizePolicy().hasHeightForWidth())
        self.scroll_export.setSizePolicy(sizePolicy)
        self.scroll_export.setMaximumSize(QtCore.QSize(16777215, 180))
        self.scroll_export.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scroll_export.setWidgetResizable(True)
        self.scroll_export.setObjectName("scroll_export")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 700, 180))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.groupBox_7 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_7.sizePolicy().hasHeightForWidth())
        self.groupBox_7.setSizePolicy(sizePolicy)
        self.groupBox_7.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_16.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setContentsMargins(0, 0, -1, -1)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setContentsMargins(0, 0, -1, -1)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.gridLayout_16 = QtWidgets.QGridLayout()
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.tool_output_file = QtWidgets.QToolButton(self.groupBox_7)
        self.tool_output_file.setObjectName("tool_output_file")
        self.gridLayout_16.addWidget(self.tool_output_file, 0, 2, 1, 1, QtCore.Qt.AlignLeft)
        self.rb_export_red = QtWidgets.QRadioButton(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_export_red.sizePolicy().hasHeightForWidth())
        self.rb_export_red.setSizePolicy(sizePolicy)
        self.rb_export_red.setMaximumSize(QtCore.QSize(82, 16777215))
        self.rb_export_red.setChecked(True)
        self.rb_export_red.setObjectName("rb_export_red")
        self.gridLayout_16.addWidget(self.rb_export_red, 1, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.lab_output_2 = QtWidgets.QLabel(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_output_2.sizePolicy().hasHeightForWidth())
        self.lab_output_2.setSizePolicy(sizePolicy)
        self.lab_output_2.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lab_output_2.setObjectName("lab_output_2")
        self.gridLayout_16.addWidget(self.lab_output_2, 0, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.txt_output_file = QtWidgets.QLineEdit(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_output_file.sizePolicy().hasHeightForWidth())
        self.txt_output_file.setSizePolicy(sizePolicy)
        self.txt_output_file.setMinimumSize(QtCore.QSize(150, 0))
        self.txt_output_file.setMaximumSize(QtCore.QSize(1200, 16777215))
        self.txt_output_file.setObjectName("txt_output_file")
        self.gridLayout_16.addWidget(self.txt_output_file, 0, 1, 1, 1)
        self.rb_export_n = QtWidgets.QRadioButton(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_export_n.sizePolicy().hasHeightForWidth())
        self.rb_export_n.setSizePolicy(sizePolicy)
        self.rb_export_n.setMaximumSize(QtCore.QSize(55, 16777215))
        self.rb_export_n.setObjectName("rb_export_n")
        self.gridLayout_16.addWidget(self.rb_export_n, 2, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.txt_para_exp_n = QtWidgets.QLineEdit(self.groupBox_7)
        self.txt_para_exp_n.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_para_exp_n.sizePolicy().hasHeightForWidth())
        self.txt_para_exp_n.setSizePolicy(sizePolicy)
        self.txt_para_exp_n.setMaximumSize(QtCore.QSize(50, 16777215))
        self.txt_para_exp_n.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txt_para_exp_n.setObjectName("txt_para_exp_n")
        self.gridLayout_16.addWidget(self.txt_para_exp_n, 2, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.txt_para_exp_red = QtWidgets.QLineEdit(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_para_exp_red.sizePolicy().hasHeightForWidth())
        self.txt_para_exp_red.setSizePolicy(sizePolicy)
        self.txt_para_exp_red.setMaximumSize(QtCore.QSize(30, 16777215))
        self.txt_para_exp_red.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txt_para_exp_red.setObjectName("txt_para_exp_red")
        self.horizontalLayout_20.addWidget(self.txt_para_exp_red, 0, QtCore.Qt.AlignLeft)
        self.lab_export_red = QtWidgets.QLabel(self.groupBox_7)
        self.lab_export_red.setObjectName("lab_export_red")
        self.horizontalLayout_20.addWidget(self.lab_export_red, 0, QtCore.Qt.AlignLeft)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem24)
        self.gridLayout_16.addLayout(self.horizontalLayout_20, 1, 1, 1, 1)
        self.verticalLayout_20.addLayout(self.gridLayout_16)
        spacerItem25 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_20.addItem(spacerItem25)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        spacerItem26 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem26)
        self.cb_save_pic_export = QtWidgets.QCheckBox(self.groupBox_7)
        self.cb_save_pic_export.setObjectName("cb_save_pic_export")
        self.horizontalLayout_22.addWidget(self.cb_save_pic_export)
        self.but_plot_export = QtWidgets.QPushButton(self.groupBox_7)
        self.but_plot_export.setObjectName("but_plot_export")
        self.horizontalLayout_22.addWidget(self.but_plot_export)
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem27)
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem28)
        self.but_export = QtWidgets.QPushButton(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.but_export.sizePolicy().hasHeightForWidth())
        self.but_export.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.but_export.setFont(font)
        self.but_export.setObjectName("but_export")
        self.horizontalLayout_22.addWidget(self.but_export)
        self.verticalLayout_20.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_14.addLayout(self.verticalLayout_20)
        spacerItem29 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem29)
        self.verticalLayout_16.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_27.addWidget(self.groupBox_7)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(127, 16777215))
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.list_data = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_data.sizePolicy().hasHeightForWidth())
        self.list_data.setSizePolicy(sizePolicy)
        self.list_data.setMinimumSize(QtCore.QSize(100, 0))
        self.list_data.setMaximumSize(QtCore.QSize(150, 16777215))
        self.list_data.setAutoFillBackground(False)
        self.list_data.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.list_data.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.list_data.setAlternatingRowColors(True)
        self.list_data.setObjectName("list_data")
        self.verticalLayout_3.addWidget(self.list_data)
        self.horizontalLayout_27.addLayout(self.verticalLayout_3)
        self.verticalLayout_11.addLayout(self.horizontalLayout_27)
        self.scroll_export.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_14.addWidget(self.scroll_export)
        self.verticalLayout.addLayout(self.verticalLayout_14)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setContentsMargins(-1, 5, -1, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.but_collapse_auto = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.but_collapse_auto.setFont(font)
        self.but_collapse_auto.setObjectName("but_collapse_auto")
        self.horizontalLayout_26.addWidget(self.but_collapse_auto)
        spacerItem30 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem30)
        self.verticalLayout_15.addLayout(self.horizontalLayout_26)
        self.scroll_auto = QtWidgets.QScrollArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scroll_auto.sizePolicy().hasHeightForWidth())
        self.scroll_auto.setSizePolicy(sizePolicy)
        self.scroll_auto.setMaximumSize(QtCore.QSize(16777215, 0))
        self.scroll_auto.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scroll_auto.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.scroll_auto.setWidgetResizable(True)
        self.scroll_auto.setObjectName("scroll_auto")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 683, 186))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.groupBox_6 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.cb_save_pic_auto = QtWidgets.QCheckBox(self.groupBox_6)
        self.cb_save_pic_auto.setObjectName("cb_save_pic_auto")
        self.verticalLayout_18.addWidget(self.cb_save_pic_auto)
        self.but_auto_prep = QtWidgets.QPushButton(self.groupBox_6)
        self.but_auto_prep.setObjectName("but_auto_prep")
        self.verticalLayout_18.addWidget(self.but_auto_prep)
        self.but_auto_filt = QtWidgets.QPushButton(self.groupBox_6)
        self.but_auto_filt.setObjectName("but_auto_filt")
        self.verticalLayout_18.addWidget(self.but_auto_filt)
        self.but_auto_cof = QtWidgets.QPushButton(self.groupBox_6)
        self.but_auto_cof.setObjectName("but_auto_cof")
        self.verticalLayout_18.addWidget(self.but_auto_cof)
        self.but_auto_export = QtWidgets.QPushButton(self.groupBox_6)
        self.but_auto_export.setObjectName("but_auto_export")
        self.verticalLayout_18.addWidget(self.but_auto_export)
        self.horizontalLayout_10.addWidget(self.groupBox_6)
        self.gb_batch = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.gb_batch.setEnabled(False)
        self.gb_batch.setCheckable(True)
        self.gb_batch.setChecked(False)
        self.gb_batch.setObjectName("gb_batch")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.gb_batch)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.gridLayout_17 = QtWidgets.QGridLayout()
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.lab_source_2 = QtWidgets.QLabel(self.gb_batch)
        self.lab_source_2.setObjectName("lab_source_2")
        self.gridLayout_17.addWidget(self.lab_source_2, 0, 0, 1, 1)
        self.tool_input_batch = QtWidgets.QToolButton(self.gb_batch)
        self.tool_input_batch.setObjectName("tool_input_batch")
        self.gridLayout_17.addWidget(self.tool_input_batch, 0, 2, 1, 1)
        self.txt_input_batch = QtWidgets.QLineEdit(self.gb_batch)
        self.txt_input_batch.setMinimumSize(QtCore.QSize(200, 0))
        self.txt_input_batch.setFrame(True)
        self.txt_input_batch.setDragEnabled(False)
        self.txt_input_batch.setClearButtonEnabled(False)
        self.txt_input_batch.setObjectName("txt_input_batch")
        self.gridLayout_17.addWidget(self.txt_input_batch, 0, 1, 1, 1)
        self.lab_output = QtWidgets.QLabel(self.gb_batch)
        self.lab_output.setObjectName("lab_output")
        self.gridLayout_17.addWidget(self.lab_output, 1, 0, 1, 1)
        self.txt_output_batch = QtWidgets.QLineEdit(self.gb_batch)
        self.txt_output_batch.setMinimumSize(QtCore.QSize(200, 0))
        self.txt_output_batch.setObjectName("txt_output_batch")
        self.gridLayout_17.addWidget(self.txt_output_batch, 1, 1, 1, 1)
        self.tool_output_batch = QtWidgets.QToolButton(self.gb_batch)
        self.tool_output_batch.setObjectName("tool_output_batch")
        self.gridLayout_17.addWidget(self.tool_output_batch, 1, 2, 1, 1)
        self.verticalLayout_10.addLayout(self.gridLayout_17)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setContentsMargins(10, -1, -1, -1)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        spacerItem31 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem31)
        self.cb_save_pic_batch = QtWidgets.QCheckBox(self.gb_batch)
        self.cb_save_pic_batch.setObjectName("cb_save_pic_batch")
        self.horizontalLayout_19.addWidget(self.cb_save_pic_batch)
        spacerItem32 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem32)
        self.but_batch = QtWidgets.QPushButton(self.gb_batch)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.but_batch.sizePolicy().hasHeightForWidth())
        self.but_batch.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.but_batch.setFont(font)
        self.but_batch.setCheckable(False)
        self.but_batch.setObjectName("but_batch")
        self.horizontalLayout_19.addWidget(self.but_batch)
        spacerItem33 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem33)
        self.verticalLayout_10.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_10.addWidget(self.gb_batch)
        self.verticalLayout_9.addLayout(self.horizontalLayout_10)
        self.scroll_auto.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_15.addWidget(self.scroll_auto)
        self.verticalLayout.addLayout(self.verticalLayout_15)
        self.layout_buttons = QtWidgets.QHBoxLayout()
        self.layout_buttons.setObjectName("layout_buttons")
        self.but_cancel = QtWidgets.QPushButton(self.centralwidget)
        self.but_cancel.setObjectName("but_cancel")
        self.layout_buttons.addWidget(self.but_cancel)
        spacerItem34 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_buttons.addItem(spacerItem34)
        self.but_debug = QtWidgets.QPushButton(self.centralwidget)
        self.but_debug.setObjectName("but_debug")
        self.layout_buttons.addWidget(self.but_debug)
        self.verticalLayout.addLayout(self.layout_buttons)
        UMT_Auswertung.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(UMT_Auswertung)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 720, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEinstellugnen = QtWidgets.QMenu(self.menubar)
        self.menuEinstellugnen.setObjectName("menuEinstellugnen")
        UMT_Auswertung.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(UMT_Auswertung)
        self.statusbar.setObjectName("statusbar")
        UMT_Auswertung.setStatusBar(self.statusbar)
        self.actionOpen_File = QtWidgets.QAction(UMT_Auswertung)
        self.actionOpen_File.setObjectName("actionOpen_File")
        self.actionOpen_Folder = QtWidgets.QAction(UMT_Auswertung)
        self.actionOpen_Folder.setObjectName("actionOpen_Folder")
        self.actionQuit = QtWidgets.QAction(UMT_Auswertung)
        self.actionQuit.setObjectName("actionQuit")
        self.actionExport = QtWidgets.QAction(UMT_Auswertung)
        self.actionExport.setObjectName("actionExport")
        self.actionSave_Setting = QtWidgets.QAction(UMT_Auswertung)
        self.actionSave_Setting.setObjectName("actionSave_Setting")
        self.actionLoad_Setting = QtWidgets.QAction(UMT_Auswertung)
        self.actionLoad_Setting.setObjectName("actionLoad_Setting")
        self.actionSpeichern = QtWidgets.QAction(UMT_Auswertung)
        self.actionSpeichern.setObjectName("actionSpeichern")
        self.actionLaden = QtWidgets.QAction(UMT_Auswertung)
        self.actionLaden.setObjectName("actionLaden")
        self.menuFile.addAction(self.actionOpen_File)
        self.menuFile.addAction(self.actionOpen_Folder)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExport)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuEinstellugnen.addAction(self.actionSpeichern)
        self.menuEinstellugnen.addAction(self.actionLaden)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEinstellugnen.menuAction())

        self.retranslateUi(UMT_Auswertung)
        self.actionQuit.triggered.connect(UMT_Auswertung.close)
        self.but_cancel.clicked.connect(UMT_Auswertung.close)
        QtCore.QMetaObject.connectSlotsByName(UMT_Auswertung)
        UMT_Auswertung.setTabOrder(self.txt_input_file, self.tool_input_file)
        UMT_Auswertung.setTabOrder(self.tool_input_file, self.but_clear_data)
        UMT_Auswertung.setTabOrder(self.but_clear_data, self.txt_output_pics)
        UMT_Auswertung.setTabOrder(self.txt_output_pics, self.tool_output_pics)
        UMT_Auswertung.setTabOrder(self.tool_output_pics, self.txt_para_frequency)
        UMT_Auswertung.setTabOrder(self.txt_para_frequency, self.txt_para_hub)
        UMT_Auswertung.setTabOrder(self.txt_para_hub, self.but_calc_s)
        UMT_Auswertung.setTabOrder(self.but_calc_s, self.cb_save_pic_raw)
        UMT_Auswertung.setTabOrder(self.cb_save_pic_raw, self.but_plot_raw)
        UMT_Auswertung.setTabOrder(self.but_plot_raw, self.but_collapse_settings)
        UMT_Auswertung.setTabOrder(self.but_collapse_settings, self.txt_para_min_thresh)
        UMT_Auswertung.setTabOrder(self.txt_para_min_thresh, self.txt_para_min_dist)
        UMT_Auswertung.setTabOrder(self.txt_para_min_dist, self.txt_para_min_n)
        UMT_Auswertung.setTabOrder(self.txt_para_min_n, self.txt_para_min_pos)
        UMT_Auswertung.setTabOrder(self.txt_para_min_pos, self.cb_save_pic_min)
        UMT_Auswertung.setTabOrder(self.cb_save_pic_min, self.but_plot_min)
        UMT_Auswertung.setTabOrder(self.but_plot_min, self.but_min_ok)
        UMT_Auswertung.setTabOrder(self.but_min_ok, self.txt_para_dist_thresh)
        UMT_Auswertung.setTabOrder(self.txt_para_dist_thresh, self.txt_para_dist_off)
        UMT_Auswertung.setTabOrder(self.txt_para_dist_off, self.cb_save_pic_dist)
        UMT_Auswertung.setTabOrder(self.cb_save_pic_dist, self.but_plot_dist)
        UMT_Auswertung.setTabOrder(self.but_plot_dist, self.but_dist_ok)
        UMT_Auswertung.setTabOrder(self.but_dist_ok, self.txt_para_area_shift)
        UMT_Auswertung.setTabOrder(self.txt_para_area_shift, self.txt_para_area_n)
        UMT_Auswertung.setTabOrder(self.txt_para_area_n, self.txt_para_area_pos)
        UMT_Auswertung.setTabOrder(self.txt_para_area_pos, self.cb_save_pic_area)
        UMT_Auswertung.setTabOrder(self.cb_save_pic_area, self.but_plot_area)
        UMT_Auswertung.setTabOrder(self.but_plot_area, self.but_area_ok)
        UMT_Auswertung.setTabOrder(self.but_area_ok, self.rb_filt_sav)
        UMT_Auswertung.setTabOrder(self.rb_filt_sav, self.rb_filt_roll)
        UMT_Auswertung.setTabOrder(self.rb_filt_roll, self.rb_filt_med)
        UMT_Auswertung.setTabOrder(self.rb_filt_med, self.txt_para_filt_n_sav)
        UMT_Auswertung.setTabOrder(self.txt_para_filt_n_sav, self.txt_para_filt_p_sav)
        UMT_Auswertung.setTabOrder(self.txt_para_filt_p_sav, self.txt_para_filt_n_roll)
        UMT_Auswertung.setTabOrder(self.txt_para_filt_n_roll, self.txt_para_filt_n_med)
        UMT_Auswertung.setTabOrder(self.txt_para_filt_n_med, self.cb_save_pic_filt)
        UMT_Auswertung.setTabOrder(self.cb_save_pic_filt, self.but_plot_filt)
        UMT_Auswertung.setTabOrder(self.but_plot_filt, self.but_filt_ok)
        UMT_Auswertung.setTabOrder(self.but_filt_ok, self.rb_cof_t)
        UMT_Auswertung.setTabOrder(self.rb_cof_t, self.rb_cof_s)
        UMT_Auswertung.setTabOrder(self.rb_cof_s, self.txt_para_cof_start)
        UMT_Auswertung.setTabOrder(self.txt_para_cof_start, self.txt_para_cof_end)
        UMT_Auswertung.setTabOrder(self.txt_para_cof_end, self.cb_save_pic_cof)
        UMT_Auswertung.setTabOrder(self.cb_save_pic_cof, self.but_plot_cof)
        UMT_Auswertung.setTabOrder(self.but_plot_cof, self.but_cof_ok)
        UMT_Auswertung.setTabOrder(self.but_cof_ok, self.but_collapse_export)
        UMT_Auswertung.setTabOrder(self.but_collapse_export, self.txt_output_file)
        UMT_Auswertung.setTabOrder(self.txt_output_file, self.tool_output_file)
        UMT_Auswertung.setTabOrder(self.tool_output_file, self.rb_export_red)
        UMT_Auswertung.setTabOrder(self.rb_export_red, self.rb_export_n)
        UMT_Auswertung.setTabOrder(self.rb_export_n, self.txt_para_exp_red)
        UMT_Auswertung.setTabOrder(self.txt_para_exp_red, self.txt_para_exp_n)
        UMT_Auswertung.setTabOrder(self.txt_para_exp_n, self.cb_save_pic_export)
        UMT_Auswertung.setTabOrder(self.cb_save_pic_export, self.but_plot_export)
        UMT_Auswertung.setTabOrder(self.but_plot_export, self.but_export)
        UMT_Auswertung.setTabOrder(self.but_export, self.list_data)
        UMT_Auswertung.setTabOrder(self.list_data, self.but_collapse_auto)
        UMT_Auswertung.setTabOrder(self.but_collapse_auto, self.cb_save_pic_auto)
        UMT_Auswertung.setTabOrder(self.cb_save_pic_auto, self.but_auto_prep)
        UMT_Auswertung.setTabOrder(self.but_auto_prep, self.but_auto_filt)
        UMT_Auswertung.setTabOrder(self.but_auto_filt, self.but_auto_cof)
        UMT_Auswertung.setTabOrder(self.but_auto_cof, self.but_auto_export)
        UMT_Auswertung.setTabOrder(self.but_auto_export, self.gb_batch)
        UMT_Auswertung.setTabOrder(self.gb_batch, self.txt_input_batch)
        UMT_Auswertung.setTabOrder(self.txt_input_batch, self.tool_input_batch)
        UMT_Auswertung.setTabOrder(self.tool_input_batch, self.txt_output_batch)
        UMT_Auswertung.setTabOrder(self.txt_output_batch, self.tool_output_batch)
        UMT_Auswertung.setTabOrder(self.tool_output_batch, self.cb_save_pic_batch)
        UMT_Auswertung.setTabOrder(self.cb_save_pic_batch, self.but_batch)
        UMT_Auswertung.setTabOrder(self.but_batch, self.but_cancel)
        UMT_Auswertung.setTabOrder(self.but_cancel, self.but_debug)
        UMT_Auswertung.setTabOrder(self.but_debug, self.scroll_settings)
        UMT_Auswertung.setTabOrder(self.scroll_settings, self.scroll_export)
        UMT_Auswertung.setTabOrder(self.scroll_export, self.scroll_auto)

    def retranslateUi(self, UMT_Auswertung):
        _translate = QtCore.QCoreApplication.translate
        UMT_Auswertung.setWindowTitle(_translate("UMT_Auswertung", "UMT-Analysis"))
        self.gb_inout.setTitle(_translate("UMT_Auswertung", "Eingabedaten"))
        self.label_17.setText(_translate("UMT_Auswertung", "Bildordner"))
        self.tool_input_file.setText(_translate("UMT_Auswertung", "..."))
        self.lab_source.setText(_translate("UMT_Auswertung", "Quelldatei"))
        self.txt_input_file.setToolTip(_translate("UMT_Auswertung", "<html><head/><body><p>Pfad zur Quelldatei. </p><p>Auswahl über STRG + O, File --&gt; Open oder Toolbutton.<br/></p><p><span style=\" font-weight:600;\">ACHTUNG: </span><br/>Derzeit keine Aktualisierung der Datei, wenn Dateiname nachträglich geändert wird. </p></body></html>"))
        self.txt_input_file.setPlaceholderText(_translate("UMT_Auswertung", "C:/Pfad/zur/Quelldatei"))
        self.txt_output_pics.setToolTip(_translate("UMT_Auswertung", "<html><head/><body><p>Ordner, in dem Bilder der Diagramme allerTests gespeichert werden. <br/>Bilder werden nach Test benannt, liegen aber im gleichen Ordner.</p></body></html>"))
        self.txt_output_pics.setPlaceholderText(_translate("UMT_Auswertung", "C:/Pfad/zum/Export-Ordner/der/Diagrammbilder"))
        self.tool_output_pics.setText(_translate("UMT_Auswertung", "..."))
        self.but_clear_data.setToolTip(_translate("UMT_Auswertung", "<html><head/><body><p>Löscht alle berechneten Daten und lädt Datei aus angegebenem Pfad erneut.<br/>Hilfreich, wenn Änderungen notwendig sind. </p></body></html>"))
        self.but_clear_data.setText(_translate("UMT_Auswertung", "DATEN \n"
"NEU LADEN"))
        self.label_2.setText(_translate("UMT_Auswertung", "Frequenz"))
        self.txt_para_frequency.setToolTip(_translate("UMT_Auswertung", "<html><head/><body><p>Frequenz des Verscheißversuchs in Hz.</p><p>Wird beim Laden versucht, aus den Daten zu lesen. </p><p>Notwendig für Verschleißwegberechnung.</p></body></html>"))
        self.label_3.setText(_translate("UMT_Auswertung", "Hub"))
        self.label_18.setText(_translate("UMT_Auswertung", "Hz"))
        self.label_19.setText(_translate("UMT_Auswertung", "mm"))
        self.but_calc_s.setToolTip(_translate("UMT_Auswertung", "<html><head/><body><p>Berechnet aus Frequenz und Hub den Verschleißweg. <br/>Fügt den Daten automatisch die Spalte &quot;Verschleißweg&quot; hinzu.</p></body></html>"))
        self.but_calc_s.setText(_translate("UMT_Auswertung", "Berechne\n"
"Verschleißweg"))
        self.cb_save_pic_raw.setToolTip(_translate("UMT_Auswertung", "<html><head/><body><p>Aktivieren, wenn Diagramme gesichert werden sollen.</p><p>Falls kein Bildordner angegeben wird, erscheint Information zu Speicherort.</p></body></html>"))
        self.cb_save_pic_raw.setText(_translate("UMT_Auswertung", "Bilder"))
        self.but_plot_raw.setToolTip(_translate("UMT_Auswertung", "<html><head/><body><p>Zeigt die Rohdaten in einem Diagramm an.</p></body></html>"))
        self.but_plot_raw.setText(_translate("UMT_Auswertung", "Plot RAW"))
        self.but_collapse_settings.setText(_translate("UMT_Auswertung", "Verstecke Einstellungen"))
        self.gb_minima.setTitle(_translate("UMT_Auswertung", "Umkehrpunkte"))
        self.label_4.setText(_translate("UMT_Auswertung", "Schwellwert"))
        self.txt_para_min_dist.setToolTip(_translate("UMT_Auswertung", "<html><head/><body><p>Gibt den Abstand an, der mindestens zwischen zwei Umkehrpunkten liegen muss.<br/>Verringern, wenn Umkehrpunkte unterhalb des Schwellwerts liegen, aber dennoch nicht korrekt gefunden werden.</p></body></html>"))
        self.txt_para_min_dist.setText(_translate("UMT_Auswertung", "10"))
        self.txt_para_min_n.setToolTip(_translate("UMT_Auswertung", "<html><head/><body><p>Gibt die Anzahl der Testfenster der Rohdaten an, bei denen die Berechnung der Umkehrpunkte durchgeführt wird.<br/>Werden keine Testpositionen angegeben, werden zufällige Testfenster innerhalb der Rohdaten ausgewählt. <br/>Werden Testpositionen übergeben, wird dieser Parameter nicht beachtet.</p></body></html>"))
        self.txt_para_min_n.setText(_translate("UMT_Auswertung", "5"))
        self.label_6.setText(_translate("UMT_Auswertung", "Testanzahl"))
        self.label_5.setText(_translate("UMT_Auswertung", "Abstand"))
        self.txt_para_min_thresh.setToolTip(_translate("UMT_Auswertung", "<html><head/><body><p>Gibt an, unterhalb welchem Wert die Umkehrpunkte gesucht werden sollen. <br/>Erhöhen, wenn Umkehrpunkte beim Testen nicht korrekt gefunden werden. </p></body></html>"))
        self.txt_para_min_thresh.setText(_translate("UMT_Auswertung", "2"))
        self.label_7.setText(_translate("UMT_Auswertung", "Testposition"))
        self.txt_para_min_pos.setToolTip(_translate("UMT_Auswertung", "<html><head/><body><p>Konkrete Positionen, bei denen die Berechnung der Umkehrpunkte überprüft werden soll.<br/>Die Angabe erfolgt<span style=\" font-weight:600;\"> in Prozent der Daten</span>.<br/>Standardmäßig wird bei 1, 25, 50, 75 und 99,9% der Daten gesucht.</p></body></html>"))
        self.txt_para_min_pos.setPlaceholderText(_translate("UMT_Auswertung", "1; 25; 50; 75; 99,9"))
        self.cb_save_pic_min.setToolTip(_translate("UMT_Auswertung", "<html><head/><body><p>Aktivieren, wenn Diagramme gesichert werden sollen.</p><p>Falls kein Bildordner angegeben wird, erscheint Information zu Speicherort.</p></body></html>"))
        self.cb_save_pic_min.setText(_translate("UMT_Auswertung", "Bilder"))
        self.but_plot_min.setToolTip(_translate("UMT_Auswertung", "<html><head/><body><p>Zeigt berechnete Umkehrpunkte an definierten Positionen an und gibt Diagramme aus.</p></body></html>"))
        self.but_plot_min.setText(_translate("UMT_Auswertung", "Testen"))
        self.but_min_ok.setToolTip(_translate("UMT_Auswertung", "<html><head/><body><p>Bestätigt Richtigkeit der Berechnung der Umkehrpunkte.<br/>Weiter mit Ermittlung des Einlaufbereichs.</p></body></html>"))
        self.but_min_ok.setText(_translate("UMT_Auswertung", "Minima OK"))
        self.gb_dist.setTitle(_translate("UMT_Auswertung", "Einlaufbereich"))
        self.label_8.setText(_translate("UMT_Auswertung", "Schwellwert"))
        self.txt_para_dist_thresh.setToolTip(_translate("UMT_Auswertung", "<html><head/><body><p>Abweichung vom mittleren Abstand der Umkehrpunkte in Prozent, ab dem Abstände als konstant angesehen werden.</p></body></html>"))
        self.txt_para_dist_thresh.setText(_translate("UMT_Auswertung", "5"))
        self.label_9.setText(_translate("UMT_Auswertung", "Offset"))
        self.txt_para_dist_off.setToolTip(_translate("UMT_Auswertung", "<html><head/><body><p>Anzahl an Umkehrpunkten, die nach Ermittlung des Einlaufbereichs zusätzlich (zur Sicherheit) abgeschnitten werden sollen.</p></body></html>"))
        self.txt_para_dist_off.setText(_translate("UMT_Auswertung", "1"))
        self.cb_save_pic_dist.setToolTip(_translate("UMT_Auswertung", "<html><head/><body><p>Aktivieren, wenn Diagramme gesichert werden sollen.</p><p>Falls kein Bildordner angegeben wird, erscheint Information zu Speicherort.</p></body></html>"))
        self.cb_save_pic_dist.setText(_translate("UMT_Auswertung", "Bilder"))
        self.but_plot_dist.setToolTip(_translate("UMT_Auswertung", "<html><head/><body><p>Berechnet den Einlaufbereich der Daten anhand der Abweichung der Abstände der Umkehrpunkte vom Median aller Umkehrpunkte.<br/>Gibt ermittelten Schwellwert und Beschnittgrenze der Daten durch gewählten Offset aus.</p></body></html>"))
        self.but_plot_dist.setText(_translate("UMT_Auswertung", "Testen"))
        self.but_dist_ok.setToolTip(_translate("UMT_Auswertung", "<html><head/><body><p>Bestätigt Richtigkeit des Einlaufbereichs.<br/>Weiter mit Auswahl der Berechnungsgrenzen für den Verschleißkoeffizienten.</p></body></html>"))
        self.but_dist_ok.setText(_translate("UMT_Auswertung", "Einlauf OK"))
        self.gb_area.setTitle(_translate("UMT_Auswertung", "Beschnitt"))
        self.txt_para_area_shift.setToolTip(_translate("UMT_Auswertung", "<html><head/><body><p>Anzahl der Punkte, die um die Umkehrpunkte weggeschnitten werden sollen.<br/>Sollte so klein als möglich sein. </p></body></html>"))
        self.txt_para_area_shift.setText(_translate("UMT_Auswertung", "5"))
        self.txt_para_area_n.setToolTip(_translate("UMT_Auswertung", "<html><head/><body><p>Gibt die Anzahl der Testfenster der Rohdaten an, bei denen die Visualisierung des Beschnittfensters ausgegeben wird.<br/>Werden keine Testpositionen angegeben, werden zufällige Testfenster innerhalb der Rohdaten ausgewählt. <br/>Werden Testpositionen übergeben, wird dieser Parameter nicht beachtet.</p></body></html>"))
        self.txt_para_area_n.setText(_translate("UMT_Auswertung", "3"))
        self.label_10.setText(_translate("UMT_Auswertung", "Versatz"))
        self.label_11.setText(_translate("UMT_Auswertung", "Testanzahl"))
        self.label_12.setText(_translate("UMT_Auswertung", "Testposition"))
        self.txt_para_area_pos.setToolTip(_translate("UMT_Auswertung", "<html><head/><body><p>Konkrete Positionen, bei denen die Lage der Berechnungsintervalle überprüft werden soll.<br/>Die Angabe erfolgt<span style=\" font-weight:600;\"> in Prozent der Daten</span>.<br/>Standardmäßig wird bei 1, 25, 50, 75 und 99,9% der Daten gesucht.</p></body></html>"))
        self.txt_para_area_pos.setPlaceholderText(_translate("UMT_Auswertung", "0,01; 25; 50; 75; 99,9"))
        self.cb_save_pic_area.setToolTip(_translate("UMT_Auswertung", "<html><head/><body><p>Aktivieren, wenn Diagramme gesichert werden sollen.</p><p>Falls kein Bildordner angegeben wird, erscheint Information zu Speicherort.</p></body></html>"))
        self.cb_save_pic_area.setText(_translate("UMT_Auswertung", "Bilder"))
        self.but_plot_area.setToolTip(_translate("UMT_Auswertung", "<html><head/><body><p>Gibt die konfigurierte Zahl von Testdaten an, in denen das Fenster für die Datenberechnung visualisiert wird. <br/>Zur Unterstützung wird der Median innerhalb des Berechnungsfensters ausgegeben.</p></body></html>"))
        self.but_plot_area.setText(_translate("UMT_Auswertung", "Testen"))
        self.but_area_ok.setText(_translate("UMT_Auswertung", "Area OK"))
        self.gb_filter.setTitle(_translate("UMT_Auswertung", "Filter zur Berechnung des Reibkoeffizienten"))
        self.rb_filt_roll.setToolTip(_translate("UMT_Auswertung", "<html><head/><body><p>Berechnet den gleitenden Durchschnitt innerhalb der Beschnittenen Daten.<br/>Daten müssen um Anzahl der Punkte reduziert werden.</p></body></html>"))
        self.rb_filt_roll.setText(_translate("UMT_Auswertung", "Gleitender Durchschnitt"))
        self.rb_filt_sav.setToolTip(_translate("UMT_Auswertung", "<html><head/><body><p>Stabiler Filter für große Datenmengen. <br/>Durch polynomische Interpolation gut konfigurierbar. </p></body></html>"))
        self.rb_filt_sav.setText(_translate("UMT_Auswertung", "Savgol-Filter"))
        self.lab_p_sav.setText(_translate("UMT_Auswertung", "Polynom"))
        self.txt_para_filt_n_sav.setToolTip(_translate("UMT_Auswertung", "Anzahl der Punkte für das Berechnungsfenster. Darf nur ungerade Werte annehmen. "))
        self.txt_para_filt_n_sav.setText(_translate("UMT_Auswertung", "501"))
        self.lab_n_sav.setText(_translate("UMT_Auswertung", "Punkte"))
        self.txt_para_filt_n_roll.setToolTip(_translate("UMT_Auswertung", "Anzahl der Punkte, über die der gleitende Durchschnitt gebildet wird."))
        self.txt_para_filt_n_roll.setText(_translate("UMT_Auswertung", "500"))
        self.txt_para_filt_p_sav.setToolTip(_translate("UMT_Auswertung", "Grad des Polynoms. Darf nicht größer als die Punktanzahl sein. "))
        self.txt_para_filt_p_sav.setText(_translate("UMT_Auswertung", "3"))
        self.lab_n_roll.setText(_translate("UMT_Auswertung", "Punkte"))
        self.rb_filt_med.setToolTip(_translate("UMT_Auswertung", "<html><head/><body><p>Berechnet den Median der angegebenen Punkte innerhalb des Berechnungsfensters. </p></body></html>"))
        self.rb_filt_med.setText(_translate("UMT_Auswertung", "Median-Filter"))
        self.lab_n_med.setText(_translate("UMT_Auswertung", "Punkte"))
        self.txt_para_filt_n_med.setToolTip(_translate("UMT_Auswertung", "Anzahl der Punkte für die Berechnung des Medians. Sollte ungerade sein."))
        self.txt_para_filt_n_med.setText(_translate("UMT_Auswertung", "501"))
        self.cb_save_pic_filt.setToolTip(_translate("UMT_Auswertung", "<html><head/><body><p>Aktivieren, wenn Diagramme gesichert werden sollen.</p><p>Falls kein Bildordner angegeben wird, erscheint Information zu Speicherort.</p></body></html>"))
        self.cb_save_pic_filt.setText(_translate("UMT_Auswertung", "Bilder"))
        self.but_plot_filt.setToolTip(_translate("UMT_Auswertung", "Filtert die Daten und gibt die Roh- und gefilterten Daten in einem Diagramm aus."))
        self.but_plot_filt.setText(_translate("UMT_Auswertung", "Testen"))
        self.but_filt_ok.setToolTip(_translate("UMT_Auswertung", "<html><head/><body><p>Bestätigt die Richtigkeit der Filtereinstellungen.<br/>Weiter mit der Berechnung des statischen Reibkoeffizienten.</p></body></html>"))
        self.but_filt_ok.setText(_translate("UMT_Auswertung", "Filter OK"))
        self.gb_cof.setTitle(_translate("UMT_Auswertung", "Statischer Reibkoeffizient"))
        self.rb_cof_t.setToolTip(_translate("UMT_Auswertung", "<html><head/><body><p>Statischer Reibkoeffizient soll aus Zeitdaten berechnet werden (keine Angabe der Prüffrequenz oder des Hubs notwendig).</p></body></html>"))
        self.rb_cof_t.setText(_translate("UMT_Auswertung", "x = t"))
        self.rb_cof_s.setToolTip(_translate("UMT_Auswertung", "<html><head/><body><p>Statischer Reibkoeffizient soll aus Verschleißweg berechnet werden (Angabe der Prüffrequenz und des Hubs notwendig).</p></body></html>"))
        self.rb_cof_s.setText(_translate("UMT_Auswertung", "x = s"))
        self.lab_cof_end.setText(_translate("UMT_Auswertung", "s"))
        self.label_26.setText(_translate("UMT_Auswertung", "Ende"))
        self.txt_para_cof_start.setToolTip(_translate("UMT_Auswertung", "<html><head/><body><p>Untere Zeit- oder Weggrenze, bei der der statische Reibkoeffizient berechnet werden soll.</p></body></html>"))
        self.label_25.setText(_translate("UMT_Auswertung", "Anfang"))
        self.lab_cof_start.setText(_translate("UMT_Auswertung", "s"))
        self.txt_para_cof_end.setToolTip(_translate("UMT_Auswertung", "<html><head/><body><p>Obere Zeit- oder Weggrenze, bei der der statische Reibkoeffizient berechnet werden soll.</p></body></html>"))
        self.cb_save_pic_cof.setToolTip(_translate("UMT_Auswertung", "<html><head/><body><p>Aktivieren, wenn Diagramme gesichert werden sollen.</p><p>Falls kein Bildordner angegeben wird, erscheint Information zu Speicherort.</p></body></html>"))
        self.cb_save_pic_cof.setText(_translate("UMT_Auswertung", "Bilder"))
        self.but_plot_cof.setToolTip(_translate("UMT_Auswertung", "<html><head/><body><p>Gefilterte Daten werden über Zeit oder Weg geplottet.</p><p>Werden Grenzen für die Berechnung des statischen Reibkoeffizienten übergeben, erfolgt eine visuelle Ausgabe des berechneten Reibkoeffizientens. <br/>Andernfalls kann die Ausgabe zur Ermittlung der gewünschten Berechnungsgrenzen genutzt werden.</p></body></html>"))
        self.but_plot_cof.setText(_translate("UMT_Auswertung", "Testen"))
        self.but_cof_ok.setToolTip(_translate("UMT_Auswertung", "<html><head/><body><p>Bestätigt die Richtigkeit der Berechnung des Reibkoeffizienten. <br/>Fügt Exportspalte &quot;statischer Reibkoeffizient hinzu.<br/>Daten sind nun vollständig.</p></body></html>"))
        self.but_cof_ok.setText(_translate("UMT_Auswertung", "COF OK"))
        self.but_collapse_export.setText(_translate("UMT_Auswertung", "Verstecke Export"))
        self.groupBox_7.setToolTip(_translate("UMT_Auswertung", "<html><head/><body><p>In diesem Dialog werden Einstellungen zum Export der Excel-Datei getroffen.</p></body></html>"))
        self.groupBox_7.setTitle(_translate("UMT_Auswertung", "Exporteinstellungen"))
        self.tool_output_file.setText(_translate("UMT_Auswertung", "..."))
        self.rb_export_red.setText(_translate("UMT_Auswertung", "Reduzierung"))
        self.lab_output_2.setText(_translate("UMT_Auswertung", "Output"))
        self.txt_output_file.setToolTip(_translate("UMT_Auswertung", "Pfad zum Output der Exceldaten."))
        self.txt_output_file.setPlaceholderText(_translate("UMT_Auswertung", "C:/Pfad/zur/Exceldatei"))
        self.rb_export_n.setText(_translate("UMT_Auswertung", "Punkte"))
        self.txt_para_exp_n.setToolTip(_translate("UMT_Auswertung", "Es werden x Punkte in die Exceldatei geschrieben."))
        self.txt_para_exp_red.setToolTip(_translate("UMT_Auswertung", "Es wird nur jeder x-te Punkt in die Exceldatei geschrieben."))
        self.txt_para_exp_red.setText(_translate("UMT_Auswertung", "10"))
        self.lab_export_red.setText(_translate("UMT_Auswertung", "x"))
        self.cb_save_pic_export.setToolTip(_translate("UMT_Auswertung", "<html><head/><body><p>Aktivieren, wenn Diagramme gesichert werden sollen.</p><p>Falls kein Bildordner angegeben wird, erscheint Information zu Speicherort.</p></body></html>"))
        self.cb_save_pic_export.setText(_translate("UMT_Auswertung", "Bilder"))
        self.but_plot_export.setToolTip(_translate("UMT_Auswertung", "<html><head/><body><p>Zeigt zwei gewünschte Spalten mit entsprechenden Ausdünnung der Messwerte an. </p></body></html>"))
        self.but_plot_export.setText(_translate("UMT_Auswertung", "Testen"))
        self.but_export.setToolTip(_translate("UMT_Auswertung", "Exportiert die ausgewählten Spalten in eine Exceldatei."))
        self.but_export.setText(_translate("UMT_Auswertung", "Export"))
        self.label.setText(_translate("UMT_Auswertung", "Zu exportierende Spalten"))
        self.but_collapse_auto.setText(_translate("UMT_Auswertung", "Zeige Automation"))
        self.groupBox_6.setTitle(_translate("UMT_Auswertung", "Automatische Funktionen"))
        self.cb_save_pic_auto.setText(_translate("UMT_Auswertung", "Speichere Bilder"))
        self.but_auto_prep.setToolTip(_translate("UMT_Auswertung", "Lädt Daten, findet Umkehrpunkte, schneidet Einlauf ab und legt Berechnungsfenster fest."))
        self.but_auto_prep.setText(_translate("UMT_Auswertung", "Vorbereitung"))
        self.but_auto_filt.setToolTip(_translate("UMT_Auswertung", "Erledigt vorhergehende Schritte und filtert Daten zusätzlich."))
        self.but_auto_filt.setText(_translate("UMT_Auswertung", "+ Filterung"))
        self.but_auto_cof.setToolTip(_translate("UMT_Auswertung", "Erledigt vorhergehende Schritte und berechnet den statischen Reibkoeffizienten."))
        self.but_auto_cof.setText(_translate("UMT_Auswertung", "+ Stat. Reibkoeff."))
        self.but_auto_export.setToolTip(_translate("UMT_Auswertung", "Erledigt alle vorhergehenden Schritte und exportiert Exceldaten."))
        self.but_auto_export.setText(_translate("UMT_Auswertung", "+ Export"))
        self.gb_batch.setToolTip(_translate("UMT_Auswertung", "Dieses Feature ist derzeit noch deaktiviert."))
        self.gb_batch.setTitle(_translate("UMT_Auswertung", "Stapelverarbeitung"))
        self.lab_source_2.setText(_translate("UMT_Auswertung", "Quellordner"))
        self.tool_input_batch.setText(_translate("UMT_Auswertung", "..."))
        self.txt_input_batch.setToolTip(_translate("UMT_Auswertung", "Pfad zu Quelldaten. Kann Pfade oder Dateien enthalten. "))
        self.txt_input_batch.setPlaceholderText(_translate("UMT_Auswertung", "C:/Path/to/directory/or/file"))
        self.lab_output.setText(_translate("UMT_Auswertung", "Zielordner"))
        self.txt_output_batch.setToolTip(_translate("UMT_Auswertung", "Pfad zum Output der Exceldaten."))
        self.txt_output_batch.setPlaceholderText(_translate("UMT_Auswertung", "C:/Path/to/directory/or/file"))
        self.tool_output_batch.setText(_translate("UMT_Auswertung", "..."))
        self.cb_save_pic_batch.setText(_translate("UMT_Auswertung", "Speichere Bilder"))
        self.but_batch.setText(_translate("UMT_Auswertung", "Bearbeite Stapel"))
        self.but_cancel.setToolTip(_translate("UMT_Auswertung", "Beendet Programm"))
        self.but_cancel.setText(_translate("UMT_Auswertung", "Schließen"))
        self.but_debug.setText(_translate("UMT_Auswertung", "DEBUG"))
        self.menuFile.setTitle(_translate("UMT_Auswertung", "File"))
        self.menuEinstellugnen.setTitle(_translate("UMT_Auswertung", "Einstellungen"))
        self.actionOpen_File.setText(_translate("UMT_Auswertung", "Datei öffnen"))
        self.actionOpen_File.setShortcut(_translate("UMT_Auswertung", "Ctrl+O"))
        self.actionOpen_Folder.setText(_translate("UMT_Auswertung", "Ordner öffnen"))
        self.actionOpen_Folder.setShortcut(_translate("UMT_Auswertung", "Ctrl+Shift+O"))
        self.actionQuit.setText(_translate("UMT_Auswertung", "Beenden"))
        self.actionQuit.setShortcut(_translate("UMT_Auswertung", "Ctrl+Q"))
        self.actionExport.setText(_translate("UMT_Auswertung", "Export"))
        self.actionExport.setShortcut(_translate("UMT_Auswertung", "Ctrl+E"))
        self.actionSave_Setting.setText(_translate("UMT_Auswertung", "Save Setting"))
        self.actionLoad_Setting.setText(_translate("UMT_Auswertung", "Load Setting"))
        self.actionSpeichern.setText(_translate("UMT_Auswertung", "Speichern"))
        self.actionSpeichern.setShortcut(_translate("UMT_Auswertung", "Ctrl+S"))
        self.actionLaden.setText(_translate("UMT_Auswertung", "Laden"))
        self.actionLaden.setShortcut(_translate("UMT_Auswertung", "Ctrl+L"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UMT_Auswertung = QtWidgets.QMainWindow()
    ui = Ui_UMT_Auswertung()
    ui.setupUi(UMT_Auswertung)
    UMT_Auswertung.show()
    sys.exit(app.exec_())
